name 'mosquitto'
maintainer 'Anthonius Munthi'
maintainer_email 'me@itstoni.com'
license 'MIT'
description 'Configure Eclipse Mosquitto Server'
chef_version '>= 14.0'
issues_url 'https://github.com/kilip/cookbook-mosquitto/issues'
source_url 'https://github.com/kilip/cookbook-mosquitto'
version '0.1.0'

supports 'ubuntu'
